spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sosyalMedya
    username: postgres
    password: postgres123.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
